openapi: 3.0.3
info:
  title: Backend Test API
  description: API backend con Node.js, Express, MongoDB y JWT
  version: 1.0.0
servers:
  - url: https://app-tareas-express-mongodb.onrender.com/api
    description: Servidor de producci칩n
paths:
  /auth/register:
    post:
      summary: Registrar un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [name, email, password]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Usuario registrado
        '400':
          description: Error de validaci칩n

  /auth/login:
    post:
      summary: Iniciar sesi칩n
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login exitoso
        '401':
          description: Credenciales inv치lidas

  /task:
    get:
      summary: Obtener tareas del usuario autenticado
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Lista de tareas

    post:
      summary: Crear nueva tarea
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title]
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Tarea creada

  /task/{id}:
    get:
      summary: Obtener una tarea por ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Detalles de la tarea
        '404':
          description: No encontrada

    patch:
      summary: Actualizar tarea por ID
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Tarea actualizada

    delete:
      summary: Eliminar tarea
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tarea eliminada

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
